/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school_mangment_system;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.*;

/**
 *
 * @author ahmed soliman elkomy
 */
public class StaffForm extends javax.swing.JFrame {
    
                private final String url = "jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=SWE2DB3; user=sa;password=12345";

    /**
     * Creates new form StaffForm
     */
    public StaffForm() {
        initComponents();
         try{

               Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

               }

               catch(ClassNotFoundException ex){

               JOptionPane.showMessageDialog(this,"Cannot Load JDBC Driver !!!");

               }
    }
    void reset(){
        fn_txt.setText("");
        ln_txt.setText("");
        father_name_txt.setText("");
        ssn_txt.setText("");
        birthofdate_txt.setText("");
        phone_txt.setText("");
        address_txt.setText("");
        email_txt.setText("");
        gender_btn.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender_btn = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fn_txt = new javax.swing.JTextField();
        ssn_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        father_name_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        phone_txt = new javax.swing.JTextField();
        birthofdate_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ln_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        address_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        male_btn = new javax.swing.JRadioButton();
        female_btn = new javax.swing.JRadioButton();
        back_btn = new javax.swing.JButton();
        new_btn = new javax.swing.JButton();
        save_btn = new javax.swing.JButton();
        delete_txt = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        staffrecord_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("                                                        Staff's Details");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Basic Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel1.setText("First Name :");

        fn_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fn_txtActionPerformed(evt);
            }
        });

        ssn_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssn_txtActionPerformed(evt);
            }
        });

        jLabel3.setText("SNN :");

        jLabel4.setText("Father Name :");

        father_name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                father_name_txtActionPerformed(evt);
            }
        });

        jLabel5.setText("Mobile Number: ");

        phone_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_txtActionPerformed(evt);
            }
        });

        birthofdate_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthofdate_txtActionPerformed(evt);
            }
        });

        jLabel6.setText("Date Of Birth :");

        ln_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ln_txtActionPerformed(evt);
            }
        });

        jLabel7.setText("Last Name :");

        jLabel8.setText("E-Mail: ");

        email_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_txtActionPerformed(evt);
            }
        });

        address_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_txtActionPerformed(evt);
            }
        });

        jLabel9.setText("Address :");

        jLabel10.setText("Gender :");

        gender_btn.add(male_btn);
        male_btn.setText("male");

        gender_btn.add(female_btn);
        female_btn.setText("female");
        female_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female_btnActionPerformed(evt);
            }
        });

        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        new_btn.setText("New");
        new_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_btnActionPerformed(evt);
            }
        });

        save_btn.setText("Save");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });

        delete_txt.setText("delete");
        delete_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_txtActionPerformed(evt);
            }
        });

        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        staffrecord_btn.setText("Staff Record");
        staffrecord_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffrecord_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(fn_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ssn_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(address_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))))
                .addGap(132, 132, 132)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(birthofdate_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ln_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(father_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(male_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(female_btn))
                            .addComponent(phone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(106, 106, 106))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(back_btn)
                .addGap(51, 51, 51)
                .addComponent(new_btn)
                .addGap(58, 58, 58)
                .addComponent(save_btn)
                .addGap(72, 72, 72)
                .addComponent(delete_txt)
                .addGap(69, 69, 69)
                .addComponent(update_btn)
                .addGap(71, 71, 71)
                .addComponent(staffrecord_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fn_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ssn_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(address_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ln_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(birthofdate_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(father_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(male_btn)
                            .addComponent(female_btn))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_btn)
                    .addComponent(new_btn)
                    .addComponent(save_btn)
                    .addComponent(update_btn)
                    .addComponent(delete_txt)
                    .addComponent(staffrecord_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fn_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fn_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fn_txtActionPerformed

    private void ssn_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssn_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssn_txtActionPerformed

    private void father_name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_father_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_father_name_txtActionPerformed

    private void phone_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_txtActionPerformed

    private void birthofdate_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthofdate_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthofdate_txtActionPerformed

    private void ln_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ln_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ln_txtActionPerformed

    private void email_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_txtActionPerformed

    private void address_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_txtActionPerformed

    private void female_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_female_btnActionPerformed

    private void staffrecord_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffrecord_btnActionPerformed
        // TODO add your handling code here:
        StaffRecord record=new StaffRecord();
        this.hide();
        record.setVisible(true);
    }//GEN-LAST:event_staffrecord_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        MainMenu menu=new MainMenu();
        this.hide();
        menu.setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    private void new_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_btnActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_new_btnActionPerformed

    private void delete_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_txtActionPerformed
        // TODO add your handling code here:
        String ssn =ssn_txt.getText();
        if (ssn.isEmpty()){
            
             JOptionPane.showMessageDialog(this,"Please Enter worker ssn");
             return;
        }
        Connection con = null;
        Statement stmt = null;
        try{
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            String query ="DELET FROM staffs_record WHERE ssn ='"+ssn+"'";
           int affectRows =  stmt.executeUpdate(query);
           if (affectRows==1){
            JOptionPane.showMessageDialog(this,"successful deletion");
           
           }
           else{
            JOptionPane.showMessageDialog(this,"invalid worker ssn");
           
           }
        
        }catch(Exception ex){
         JOptionPane.showMessageDialog(this,ex.getMessage());
        
        }
        
        finally{
            if (con!=null){try{con.close();}catch(Exception ex ){}}
            if (stmt!=null){try{stmt.close();}catch(Exception ex ){}}
        
        }
        
    }//GEN-LAST:event_delete_txtActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
                String fn = fn_txt.getText();
                String ln =ln_txt.getText();
                String father_name = father_name_txt.getText();
                String ssn =  ssn_txt.getText();
                String birth_date = birthofdate_txt.getText();
                String phone = phone_txt.getText();
                String address = address_txt.getText();
                String email = email_txt.getText();
        if (ssn.isEmpty()){
            
             JOptionPane.showMessageDialog(this,"Please Enter teacher ssn");
             return;
        }
        Connection con = null;
        Statement stmt = null;
        try{
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            String query ="UPDATE  staff SET first_name ='"+fn+"' , last_name ='"+ln+"' , father_name ='"+father_name+"' , ssn ='"+ssn+"' , birth_date ='"+birth_date+"' , phone ='"+phone+"' , address ='"+address+"' , email ='"+email+"' WHERE ssn ='"+ssn+"' ";
           int affectRows =  stmt.executeUpdate(query);
           if (affectRows==1){
            JOptionPane.showMessageDialog(this,"successful updated");
           
           }
           else{
            JOptionPane.showMessageDialog(this,"invalid  worker ssn");
           
           }
        
        }catch(Exception ex){
         JOptionPane.showMessageDialog(this,ex.getMessage());
        
        }
        
        finally{
            if (con!=null){try{con.close();}catch(Exception ex ){}}
            if (stmt!=null){try{stmt.close();}catch(Exception ex ){}}
        
        }
    }//GEN-LAST:event_update_btnActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        // TODO add your handling code here:
            String fn = fn_txt.getText();
            String ln =ln_txt.getText();
            String father_name = father_name_txt.getText();
            String ssn =  ssn_txt.getText();
            String birth_date = birthofdate_txt.getText();
            String phone = phone_txt.getText();
            String address = address_txt.getText();
            String email = email_txt.getText();
                
        if (ssn.isEmpty()){
            
             JOptionPane.showMessageDialog(this,"Please Enter worker ssn");
             return;
        }
        Connection con = null;
        Statement stmt = null;
        try{
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            String query = "INSERT INTO staff VALUES('"+fn+"','"+ln+"','"+father_name+"','"+ssn+"','"+birth_date+"' , '"+phone+"' , '"+address+"','"+email+"')";
           int affectRows =  stmt.executeUpdate(query);
           if (affectRows==1){
            JOptionPane.showMessageDialog(this,"successful insertion");
           
           }
           else{
            JOptionPane.showMessageDialog(this,"please enter valid worker ssn ");
           
           }
        
        }catch(Exception ex){
         JOptionPane.showMessageDialog(this,ex.getMessage());
        
        }
        
        finally{
            if (con!=null){try{con.close();}catch(Exception ex ){}}
            if (stmt!=null){try{stmt.close();}catch(Exception ex ){}}
        
        }
        
        
    }                                        

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        String ssn =ssn_txt.getText();
        if (ssn.isEmpty()){
            
             JOptionPane.showMessageDialog(this,"Please Enter ssn");
             return;
        }
        Connection con = null;
        Statement stmt = null;
        try{
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            String query ="DELETE FROM staff WHERE ssn ='"+ssn+"'";
           int affectRows =  stmt.executeUpdate(query);
           if (affectRows==1){
            JOptionPane.showMessageDialog(this,"successful deletion");
           
           }
           else{
            JOptionPane.showMessageDialog(this,"invalid worker ssn");
           
           }
        
        }catch(Exception ex){
         JOptionPane.showMessageDialog(this,ex.getMessage());
        
        }
        
        finally{
            if (con!=null){try{con.close();}catch(Exception ex ){}}
            if (stmt!=null){try{stmt.close();}catch(Exception ex ){}}
        
        }
    }//GEN-LAST:event_save_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address_txt;
    private javax.swing.JButton back_btn;
    private javax.swing.JTextField birthofdate_txt;
    private javax.swing.JButton delete_txt;
    private javax.swing.JTextField email_txt;
    private javax.swing.JTextField father_name_txt;
    private javax.swing.JRadioButton female_btn;
    private javax.swing.JTextField fn_txt;
    private javax.swing.ButtonGroup gender_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField ln_txt;
    private javax.swing.JRadioButton male_btn;
    private javax.swing.JButton new_btn;
    private javax.swing.JTextField phone_txt;
    private javax.swing.JButton save_btn;
    private javax.swing.JTextField ssn_txt;
    private javax.swing.JButton staffrecord_btn;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
