/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school_mangment_system;

import java.sql.*;
import javax.swing.*;


/**
 *
 * @author ahmed soliman elkomy
 */
public class StudentForm extends javax.swing.JFrame {
    
            private final String url = "jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=SWE2DB3; user=sa;password=12345";

    
    /**
     * Creates new form StudentForm
     */
    public StudentForm() {
        initComponents();
         try{

               Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

               }

               catch(ClassNotFoundException ex){

               JOptionPane.showMessageDialog(this,"Cannot Load JDBC Driver !!!");

               }
    }
    void reset(){
        fn_txt.setText("");
        ln_txt.setText("");
        father_name_txt.setText("");
        fatherssn_txt.setText("");
        birthofdate_txt.setText("");
        fatherphone_txt.setText("");
        address_txt.setText("");
        email_txt.setText("");
        Gender.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fn_txt = new javax.swing.JTextField();
        fatherssn_txt = new javax.swing.JTextField();
        father_id_txt = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        father_name_txt = new javax.swing.JTextField();
        father_phone = new javax.swing.JLabel();
        fatherphone_txt = new javax.swing.JTextField();
        birthofdate_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ln_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        address_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        male_btn = new javax.swing.JRadioButton();
        female_btn = new javax.swing.JRadioButton();
        back_btn = new javax.swing.JButton();
        new_btn = new javax.swing.JButton();
        save_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        Student_record_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("                                                        Student's Details");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Basic Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel1.setText("First Name :");

        fn_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fn_txtActionPerformed(evt);
            }
        });

        fatherssn_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatherssn_txtActionPerformed(evt);
            }
        });

        father_id_txt.setText("Father SSN:");

        jLabel4.setText("Father Name :");

        father_name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                father_name_txtActionPerformed(evt);
            }
        });

        father_phone.setText("Father phone  : ");

        fatherphone_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatherphone_txtActionPerformed(evt);
            }
        });

        birthofdate_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthofdate_txtActionPerformed(evt);
            }
        });

        jLabel6.setText("Date Of Birth :");

        ln_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ln_txtActionPerformed(evt);
            }
        });

        jLabel7.setText("Last Name :");

        jLabel8.setText("E-Mail: ");

        email_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_txtActionPerformed(evt);
            }
        });

        address_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_txtActionPerformed(evt);
            }
        });

        jLabel9.setText("Address :");

        gender.setText("Gender :");

        Gender.add(male_btn);
        male_btn.setText("male");
        male_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                male_btnActionPerformed(evt);
            }
        });

        Gender.add(female_btn);
        female_btn.setText("female");
        female_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female_btnActionPerformed(evt);
            }
        });

        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        new_btn.setText("New");
        new_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_btnActionPerformed(evt);
            }
        });

        save_btn.setText("Save");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });

        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        Student_record_btn.setText("Student Record");
        Student_record_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Student_record_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fn_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(father_id_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(back_btn)
                                .addGap(67, 67, 67)
                                .addComponent(new_btn))
                            .addComponent(address_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fatherssn_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(save_btn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabel7))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(84, 84, 84)
                                    .addComponent(jLabel6))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(100, 100, 100)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(update_btn)
                                    .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(birthofdate_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ln_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(delete_btn)
                        .addGap(70, 70, 70)
                        .addComponent(Student_record_btn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(gender)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(father_phone)
                                .addGap(71, 71, 71)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fatherphone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(father_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(male_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(female_btn)))
                        .addGap(177, 177, 177))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(father_name_txt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ln_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fn_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(80, 80, 80)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(father_id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fatherssn_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthofdate_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(father_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fatherphone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(address_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(male_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(female_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(147, 147, 147)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back_btn)
                    .addComponent(new_btn)
                    .addComponent(save_btn)
                    .addComponent(update_btn)
                    .addComponent(delete_btn)
                    .addComponent(Student_record_btn))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fn_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fn_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fn_txtActionPerformed

    private void fatherssn_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatherssn_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherssn_txtActionPerformed

    private void father_name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_father_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_father_name_txtActionPerformed

    private void fatherphone_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatherphone_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherphone_txtActionPerformed

    private void birthofdate_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthofdate_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthofdate_txtActionPerformed

    private void ln_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ln_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ln_txtActionPerformed

    private void email_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_txtActionPerformed

    private void address_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_txtActionPerformed

    private void female_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_female_btnActionPerformed

    private void Student_record_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Student_record_btnActionPerformed
        // TODO add your handling code here:
        StudentRecord record=new StudentRecord();
        this.hide();
        record.setVisible(true);
    }//GEN-LAST:event_Student_record_btnActionPerformed

    private void male_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_male_btnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_male_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
          String ssn =fatherssn_txt.getText();
        if (ssn.isEmpty()){
            
             JOptionPane.showMessageDialog(this,"Please Enter father ssn");
             return;
        }
        Connection con = null;
        Statement stmt = null;
        try{
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            String query ="DELETE FROM students WHERE father_ssn ='"+ssn+"'";
           int affectRows =  stmt.executeUpdate(query);
           if (affectRows==1){
            JOptionPane.showMessageDialog(this,"successful deletion");
           
           }
           else{
            JOptionPane.showMessageDialog(this,"invalid student fathers ssn");
           
           }
        
        }catch(Exception ex){
         JOptionPane.showMessageDialog(this,ex.getMessage());
        
        }
        
        finally{
            if (con!=null){try{con.close();}catch(Exception ex ){}}
            if (stmt!=null){try{stmt.close();}catch(Exception ex ){}}
        
        }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void new_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_btnActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_new_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        MainMenu menu=new MainMenu();
        this.hide();
        menu.setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
                String fn = fn_txt.getText();
                String ln =ln_txt.getText();
                String father_name = father_name_txt.getText();
                String father_ssn =  fatherssn_txt.getText();
                String birth_date = birthofdate_txt.getText();
                String fatherphone = fatherphone_txt.getText();
                String address = address_txt.getText();
                String email = email_txt.getText();
                Object gender_txt = Gender.getSelection();
                String ssn =fatherssn_txt.getText();
        if (ssn.isEmpty()){
            
             JOptionPane.showMessageDialog(this,"Please Enter father ssn");
             return;
        }
        Connection con = null;
        Statement stmt = null;
        try{
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            String query ="UPDATE  students SET first_name ='"+fn+"' , last_name ='"+ln+"' , father_name ='"+father_name+"' , father_ssn ='"+father_ssn+"' , birth_date ='"+birth_date+"' , father_phone ='"+fatherphone+"' , address ='"+address+"' , email ='"+email+"' WHERE father_ssn ='"+father_ssn+"' ";
           int affectRows =  stmt.executeUpdate(query);
           if (affectRows==1){
            JOptionPane.showMessageDialog(this,"successful updated");
           
           }
           else{
            JOptionPane.showMessageDialog(this,"invalid student fathers ssn");
           
           }
        
        }catch(Exception ex){
         JOptionPane.showMessageDialog(this,ex.getMessage());
        
        }
        
        finally{
            if (con!=null){try{con.close();}catch(Exception ex ){}}
            if (stmt!=null){try{stmt.close();}catch(Exception ex ){}}
        
        }
        
    }//GEN-LAST:event_update_btnActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        // TODO add your handling code here:
                String fn = fn_txt.getText();
                String ln =ln_txt.getText();
                String father_name = father_name_txt.getText();
                String father_ssn =  fatherssn_txt.getText();
                String birth_date = birthofdate_txt.getText();
                String fatherphone = fatherphone_txt.getText();
                String address = address_txt.getText();
                String email = email_txt.getText();
                Object gender_txt = Gender.getSelection();
        if (fn.isEmpty()){
            
             JOptionPane.showMessageDialog(this,"Please Enter father first name");
             return;
        }
        if (ln.isEmpty()){
            
             JOptionPane.showMessageDialog(this,"Please Enter last name");
             return;
        }if (father_name.isEmpty()){
            
             JOptionPane.showMessageDialog(this,"Please Enter father name");
             return;
        }if (father_ssn.isEmpty()){
            
             JOptionPane.showMessageDialog(this,"Please Enter father ssn");
             return;
        }if (birth_date.isEmpty()){
            
             JOptionPane.showMessageDialog(this,"Please Enter date of birth");
             return;
        }if (fatherphone.isEmpty()){
            
             JOptionPane.showMessageDialog(this,"Please Enter father phone");
             return;
        }if (address.isEmpty()){
            
             JOptionPane.showMessageDialog(this,"Please Enter address");
             return;
        }if (email.isEmpty()){
            
             JOptionPane.showMessageDialog(this,"Please Enter email");
             return;
        }
        Connection con = null;
        Statement stmt = null;
        try{
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
           String query = "INSERT INTO students VALUES('"+fn+"','"+ln+"','"+father_name+"','"+father_ssn+"','"+birth_date+"' , '"+fatherphone+"' , '"+address+"','"+email+"')";
           int affectRows =  stmt.executeUpdate(query);
           if (affectRows==1){
            JOptionPane.showMessageDialog(this,"successful insertion");
           
           }
           else{
            JOptionPane.showMessageDialog(this,"please enter valid father ssn ");
           
           }
        
        }catch(Exception ex){
         JOptionPane.showMessageDialog(this,ex.getMessage());
        
        }
        
        finally{
            if (con!=null){try{con.close();}catch(Exception ex ){}}
            if (stmt!=null){try{stmt.close();}catch(Exception ex ){}}
        
        }
    }//GEN-LAST:event_save_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Gender;
    private javax.swing.JButton Student_record_btn;
    private javax.swing.JTextField address_txt;
    private javax.swing.JButton back_btn;
    private javax.swing.JTextField birthofdate_txt;
    private javax.swing.JButton delete_btn;
    private javax.swing.JTextField email_txt;
    private javax.swing.JLabel father_id_txt;
    private javax.swing.JTextField father_name_txt;
    private javax.swing.JLabel father_phone;
    private javax.swing.JTextField fatherphone_txt;
    private javax.swing.JTextField fatherssn_txt;
    private javax.swing.JRadioButton female_btn;
    private javax.swing.JTextField fn_txt;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField ln_txt;
    private javax.swing.JRadioButton male_btn;
    private javax.swing.JButton new_btn;
    private javax.swing.JButton save_btn;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
